### ISSUE TITLE
FlexStr should implement Borrow<str>

### ISSUE THREAD

**Issue by oliver-giersch** [nu11ptr/flexstr#8] opened 2022-04-01 10:18 UTC
It would be good if `FlexStr` would implement `std::borrow::Borrow<str>`. Right now you cannot use it as the key in a hashmap and look up the associated value with a regular `&str`.

**Comment by nu11ptr** [comment] 2022-04-01 12:01
Agreed - it used to. Somehow that got removed in one of the newer versions. Will ensure it gets added back.

Update: I guess this is really a regression since it used to be there, not an enhancement

**Comment by nu11ptr** [comment] 2022-04-02 16:05
Need to clean up my current checked out copy, but once that is done should only take a minute to add. I found the [commit](https://github.com/nu11ptr/flexstr/commit/9d8f365c272862626ef023e689683bb6bcca2a55#diff-0d2c98e912f3ca71b707ceb36f75f50279abd414fa5fd2e1e0265c47d2b9d7e1L597) where it was removed. Looks like it got axed for some reason during the commits pre 0.8

**Comment by nu11ptr** [comment] 2022-04-18 19:21
Fixed in 0.9.2 which was just released

**Closed as completed by nu11ptr** 2022-04-18 19:21 UTC
Labels: bug
